spring.application.name=device

# postgresql database configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://db-postgresql:5432/device}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:device}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:device}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.json

logbook.format.style=json
logging.level.org.zalando.logbook.Logbook=TRACE

server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=30s


